Added Barrel Run
Cyborg-Indians-5968/FRC2020 pull request #17
Opened 2021-02-06 19:14 UTC by lburgett

2021-02-06 19:51 UTC, jwoods7097 requested changes
Awesome job! The code looks good and we can test and fine tune this once the field is built. I've put a couple comments throughout the code suggesting some changes (though one needs to be addressed by @PathogenDavid ). One general thing:

For the autonomous methods, if we are able to do without the lambda expressions, I would add parameters to the straight driving and rotation methods, so it's easier to tweak each distance and angle. This also removes the need for having both `driveStraight()` and `driveStraightLong()`, since they do the same thing, just with different distances.

I would wait until David replies before beginning to work on the other two AutoNav courses, just in case we do need to use the lambda expressions. In the mean time, you should update the `AutonomousMode` class since each path is now its own class. Thanks again for writing this and well done on your first commit!

2021-02-06 19:51 UTC, jwoods7097 commented on src/main/java/frc/robot/AutoNavBarrel.java
> +    }
Just a formatting thing, but `periodic()` should be at the bottom of the class, since that's the order it's in in the `IRobotMode` interface.

2021-02-06 19:51 UTC, jwoods7097 commented on src/main/java/frc/robot/AutoNavBarrel.java
> +        driveStraightLong();
@PathogenDavid I know we've used lambda expressions to do autonomous steps in the past, but will this work? If it does, I feel like this would be better than having tons of methods that do almost the same thing.

2021-02-06 19:51 UTC, jwoods7097 commented on src/main/java/frc/robot/AutoNavSlolam.java
> +public class AutoNavSlolam implements IRobotMode {
Slalom is misspelled here. You should be able to fix it by renaming the class and the file.

2021-02-06 19:51 UTC, jwoods7097 commented on src/main/java/frc/robot/AutoNavBarrel.java
> +        // TODO Auto-generated method stub
This TODO statement can be removed

2021-02-06 19:59 UTC, jwoods7097 commented on src/main/java/frc/robot/AutoNavBarrel.java
> +        drive.rotateDegrees(90.0, rotationSpeed); // Turns robot to the right
This should be `lookAt()` if you're wanting to turn to an absolute angle, `rotateDegrees()` turns by a relative angle.

2021-02-09 06:10 UTC, aimiebell commented on src/main/java/frc/robot/AutoNavBounce.java
> +    public void Init() { // Bounce Auto Code
I detect that this code is problematic. According to the [Bad practice (BAD_PRACTICE)](https://spotbugs.readthedocs.io/en/stable/bugDescriptions.html#bad-practice-bad-practice), [Nm: Method names should start with a lower case letter (NM_METHOD_NAMING_CONVENTION)](https://spotbugs.readthedocs.io/en/stable/bugDescriptions.html#nm-method-names-should-start-with-a-lower-case-letter-nm-method-naming-convention).
Methods should be verbs, in mixed case with the first letter lowercase, with the first letter of each internal word capitalized.

2021-02-09 06:10 UTC, aimiebell commented on src/main/java/frc/robot/AutoNavSlolam.java
> +    public void Init() { // Slolam Auto Code
I detect that this code is problematic. According to the [Bad practice (BAD_PRACTICE)](https://spotbugs.readthedocs.io/en/stable/bugDescriptions.html#bad-practice-bad-practice), [Nm: Method names should start with a lower case letter (NM_METHOD_NAMING_CONVENTION)](https://spotbugs.readthedocs.io/en/stable/bugDescriptions.html#nm-method-names-should-start-with-a-lower-case-letter-nm-method-naming-convention).
Methods should be verbs, in mixed case with the first letter lowercase, with the first letter of each internal word capitalized.

2021-02-09 06:25 UTC, PathogenDavid commented on src/main/java/frc/robot/AutoNavBarrel.java
> +    }
Just to expand on this a little: There are four prevailing philosophies of how to order methods/functions in a file:

1. Alphabetical
2. Accessibility (IE: `private` before `protected` before `public`)
3. Chaos (AKA "Who cares, that's what code navigation tools are for". Usually things are in the order they were added.)
4. Typical call order (IE: Initialization methods followed by methods called during lifetime followed methods called at end of lifetime. For methods with no natural call order or the same natural call order there's some logical grouping. IE: All drive methods together.)

Option 4 tends to be what I use and it's really common in modern codebases, so it tends to be what you'll find in 5968 codebases.

Option 3 is also very common. The idea here tends to be that nobody reads the code linearly anyway. In my experience this isn't true in places where code reviews are done, and there are rare but not uncommon scenarios where someone needs to read all or a lot of code linearly to gain deeper understanding of it so option 4 helps understanding better.

Option 2 is more common in C++ codebases because of how accessibility works there.

Option 1 is more common in either very old code bases/companies where the code was feasibly handled in paper form more often so it made sense. It's also common when you have someone obsessed with clear-cut rules who has a say in the code base.

Personally I think option 1 is actually the worst you could possibly do. The reason being that when people go back to fix ordering mistakes in the name of obsessively following the rule, or reorder things when the name is changed. The problem with reordering is that Git and other version control systems do not (usually) understand reordering of text within source code. This breaks tools like Git blame, which let you see the history behind each line in the file. ([Example here](https://github.com/InfectedLibraries/Biohazrd/blame/2d335d872e72b8deb126ebe7aeb3246946165b60/Biohazrd/%23Declarations/TranslatedRecord.cs)) This tool can be invaluable for discovering when bugs were introduced (which can be important but is very important in safety-critical software) or for trying to figure out the hidden motivations behind a design.

As with all formatting concerns, you should try to follow the rest of the code base. (IE: Option 4 in this case.)

If you're starting a new codebase, my personal opinion is 4 > 3 > 2 > 1. And *maybe* 4 > 2 > 3 > 1 for C++.

2021-02-09 06:53 UTC, PathogenDavid commented on src/main/java/frc/robot/AutoNavBarrel.java
> +        driveStraightLong();
This will not work. The methods on `Drive` do not actually do what they say instantly, but rather schedule work to be done on the next periodic tick.

Take `driveDistance` as an example:

https://github.com/Cyborg-Indians-5968/FRC2020/blob/96e141878a538afa0eb4cd5aec4fe56dc8d05e55/src/main/java/frc/robot/Drive.java#L84-L95

Nothing in here is actually turning on the motors or waiting for the robot to finish driving `distanceInches`. Instead it's setting the state of `Drive` to go forward `distanceInches` over the next `N` `periodic` ticks.

You can see that the logic for actually driving the motors happens later on in `Drive.periodic` (using `MecanumDrive.driveCartesian`):

https://github.com/Cyborg-Indians-5968/FRC2020/blob/96e141878a538afa0eb4cd5aec4fe56dc8d05e55/src/main/java/frc/robot/Drive.java#L184-L193

This is done because the robot must do work in small chunks. You can't write code which stops the rest of the robot from running other code you wait for something to happen for many reasons, but the most important one here is communication with the driver station, which happens in the main robot loop in `Robot.startCompetition` (This method has a weird name because we didn't choose it.) Specifically here:

https://github.com/Cyborg-Indians-5968/FRC2020/blob/96e141878a538afa0eb4cd5aec4fe56dc8d05e55/src/main/java/frc/robot/Robot.java#L50

In theory you could do some evil shenanigans to manually feed the driver station and such, but this would cause other problems and would be an extremely brittle design. You should absolutely not do it.

Look at how the 2018 code base uses completion routines:

https://github.com/Cyborg-Indians-5968/FRC2018/blob/b6ba9c1055c3c3d1c355cf0f559a8f839aca39ca/src/org/usfirst/frc/team5968/robot/ScaleAuto.java#L37

You can read this as "drive 324 inches at 50% speed **and then** turn right".

What your code will do in its current form is constantly overwrite the internal state of `Drive` (which is an intentional feature to allow teleop mode interactions with `Drive` to cancel actions.) The end result is your code reads like:

> Drive 60 inches forward at 40% speed.
> Just kidding! Drive 60 inches forward at 40% speed.
> Just kidding! Turn 90 degrees at 20% speed.
> Just kidding! Drive 30 inches forward at 40% speed.
> Just kidding! Turn 90 degrees at 20% speed.
> Just kidding! Drive 30 inches forward at 40% speed.
> Just kidding! Turn 90 degrees at 20% speed.
> Just kidding! Drive 30 inches forward at 40% speed.
> Just kidding! Turn 90 degrees at 20% speed.
> Just kidding! Drive 30 inches forward at 40% speed.
> Just kidding! Drive 60 inches forward at 40% speed.
> Just kidding! Drive 30 inches forward at 40% speed.
> Just kidding! Turn 90 degrees at 20% speed.
> Just kidding! Drive 30 inches forward at 40% speed.
> Just kidding! Drive 30 inches forward at 40% speed.
> Just kidding! Turn 90 degrees at 20% speed.
> Just kidding! Drive 30 inches forward at 40% speed.
> Just kidding! Turn 90 degrees at 20% speed.
> Just kidding! Drive 30 inches forward at 40% speed.
> Just kidding! Drive 30 inches forward at 40% speed.
> Just kidding! Drive 60 inches forward at 40% speed.
> Just kidding! Turn 90 degrees at 20% speed.
> Just kidding! Drive 30 inches forward at 40% speed.
> Just kidding! Drive 60 inches forward at 40% speed.
> Just kidding! Turn 90 degrees at 20% speed.
> Just kidding! Drive 30 inches forward at 40% speed.
> Just kidding! Drive 30 inches forward at 40% speed.
> Just kidding! Turn 90 degrees at 20% speed.
> Just kidding! Drive 30 inches forward at 40% speed.
> Just kidding! Drive 60 inches forward at 40% speed.
> Just kidding! Drive 60 inches forward at 40% speed.
> Just kidding! Drive 60 inches forward at 40% speed.
> Just kidding! Drive 60 inches forward at 40% speed.

So the end result is with this code, the robot will only drive 60 inches at 40% speed and stop.

2021-02-09 06:53 UTC, PathogenDavid commented on src/main/java/frc/robot/AutoNavBarrel.java
> +        driveStraightLong();
Side note, I do not recommend reusing methods like this. (You really won't be able to once you fix the lack of completion routines anyway. But for the sake of below let's assume the current code works because we have a different implementation of `Drive` which lets it work.)

Imagine if you needed to change that initial drive straight from 120 inches to 118 inches because you find the robot is overshooting because of momentum. Well you could change `driveStraightLong` to drive 59 inches instead of 60, but now your final drive straight run is going to drive 295 inches instead of 300 inches, which (let's assume) will grossly undershoot the intended target.

Instead give names to the discrete stages of your autonomous. The robot is doing *something* here, but it's not clear what your intent is. Things like `driveToMiddleOfField`, `driveToScale`, `turnTowardsScale`, etc.

One thing you'll note from the 2018 code is that every single autonomous step is called in by only one other autonomous step, and this is basically why.

2021-02-09 06:55 UTC, PathogenDavid commented on src/main/java/frc/robot/AutoNavBounce.java
> +    public void Init() { // Bounce Auto Code
The bot is calling this a naming convention violation, but the code shouldn't even be compiling due to these typos. Make sure everything builds with no warnings or errors before committing.

2021-02-09 07:08 UTC, PathogenDavid commented
> Just in case we do need to use the lambda expressions.

Yup, you do. There theoretical designs of `Drive` which allow this code to work, but they would generally be much less flexible. (And either way you're just making `Drive` much more complex and have to worry about things it shouldn't.)

The completion routine pattern allows describing a sequence of events without an explicit state machine. Since it uses functional programming it seems more complex on the surface if you've never dealt with that before, but it is much simpler and less error-prone than conventional explicit autonomous state machine strategies. (You can see one of those in [the 2017 robot code](https://github.com/Cyborg-Indians-5968/FRC2017/blob/cb6370c0664b818bf9203d7c056bbb8b1ee8c21b/src/org/usfirst/frc/team5968/robot/AutoManager.java).)

> Thanks again for writing this and well done on your first commit!

Agreed! Don't take my walls of text as hate on your code. I just want to make sure you understand the motivations behind things rather than just telling you what to do. Autonomous code has always been difficult to get right, even when I was doing FRC back in the stone age.

Also despite the length I definitely didn't go over absolutely everything I could have. If you have questions feel free to ping me. Sorry I didn't respond sooner, GitHub is kinda terribad at telling you why a pull request is in your notifications and I was trying to clear out like 100 notifications all at once so I missed the mention.

2021-02-10 01:33 UTC, jwoods7097 commented on src/main/java/frc/robot/AutoNavBarrel.java
> +        driveStraightLong();
Thanks for the feedback! That's what I thought, but I wasn't 100% sure. @lburgett I'm almost done with improving the rotation and auto methods in `Drive`, which will make writing autonomous easier and you won't need to deal with trig functions. Once that's done you can start making these changes.

2021-02-10 03:19 UTC, lburgett commented on src/main/java/frc/robot/AutoNavBarrel.java
> +        driveStraightLong();
Thank you for the feedback as well. Very sorry for leaving a terrible commit. I am still trying to comprehend how certain aspects of the code works and such. Although I still have some questions regarding this, so @jwoods7097 I will need your help tomorrow.

2021-02-10 06:57 UTC, PathogenDavid commented on src/main/java/frc/robot/AutoNavBarrel.java
> +        driveStraightLong();
Hey nothing terrible about it! The point of the robotics team exists so you all can learn, there's no expectation that you'll produce perfect code on the first try. Like I said in my other comment, autonomous is a particularly tricky part of robot code. FRC5968 has quite literally never gotten it right on the first try, many teams don't even attempt to do anything in autonomous.

Very little non-trivial code is ever written right on the first try in general. By pure virtue of the fact that for many problems you don't know all the requirements until you start making the thing, even seasoned programmers make "terrible" decisions. If you consider Biohazrd (which is my main project I do to pay my bills right now): I wrote the original prototype in about a month back in June. In August I basically [re-wrote and re-architected the entire thing](https://github.com/InfectedLibraries/Biohazrd/commit/0726d6a2816783eea57c4c005b723986331c1843) because by the end of June I had a much better understanding of the problem space and had very different opinions on how things should be structured. Was ClangSharpTest2020 (the original name of Biohazrd) terrible? No, not really. But it was full of ill-informed design decisions that needed to be corrected for the long-term success of the project. (And they were only ill-informed in retrospect. At the time they were good decisions given the information I had.) There is some good news though, the definition of "trivial" in the first sentence changes as you get more experienced.

2021-02-10 20:51 UTC, jwoods7097 commented on src/main/java/frc/robot/AutoNavBarrel.java
> +        driveStraightLong();
This is excellent work! I'm very impressed that you were able to do all this only a month after you started to learn Java. As David said, a huge part of the experience is learning. [My first commit](https://github.com/Cyborg-Indians-5968/FRC2019/commit/f179c3fe73cb4886b047f13c357f8fcf8d7aacd9) looks simple, but it took me a day or two to write since I was still learning the libraries and how the code was structured. It starts to click and get easier as you go. This year is a challenging one to be starting in, since most of the easier stuff was written last year, and now we're working on the stuff that either I or our team has never done before, but we'll push through and get it done.

2021-02-10 22:22 UTC, jwoods7097 commented
@lburgett I have merged the drive improvements to the main repository now so you can pull those changes to your local repository and begin to make those autonomous changes. You will probably get a lot of errors since I renamed some methods to make their function clearer, so don't worry about that. I've changed `DriveDistance()` to take just a speed and an angle (in degrees) so you won't need to worry about using trig functions. Let me know if there's any questions you have or anything else you'd like me to improve.

2021-02-10 23:49 UTC, jwoods7097 reviewed
These other files look great! I know you're still working on the barrel run code so I didn't look over that. Let me know when you've finished that and I can look over it and merge it.

2021-02-10 23:49 UTC, jwoods7097 commented on src/main/java/frc/robot/AutoNavBounce.java
> +    private double forwardSpeed = 0.4;
This is probably just a remnant from your old code, but you don't need an angular speed for the new auto methods since they're controlled with PID now. Also, `forwardSpeed` can just be called `speed` since you may not always be moving forwards.

2021-02-10 23:49 UTC, jwoods7097 commented on src/main/java/frc/robot/AutoNavSlalom.java
> +    private double angularSpeed = 0.1;
See my comment in AutoNavBounce

2021-02-13 18:58 UTC, merged